import type { UserProfile, Match, Message } from './types';

// High-quality unsplash photo IDs for realistic avatars
const PHOTO_SEEDS = {
  women: [
    'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=800&q=80',
    'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&q=80',
    'https://images.unsplash.com/photo-1488716820095-cbe80883c496?w=800&q=80',
    'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80',
    'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80',
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80',
    'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80',
  ],
  men: [
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80',
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&q=80',
    'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80',
    'https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&q=80',
    'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80',
    'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&q=80',
  ],
};

export const CURRENT_USER: UserProfile = {
  id: 'user-1',
  name: 'Alex',
  age: 28,
  gender: 'man',
  location: 'San Francisco, CA',
  bio: 'Software engineer by day, amateur chef by night. I believe great conversations are as important as great food. Looking for someone who enjoys spontaneous adventures and deep 3am conversations alike.',
  occupation: 'Software Engineer',
  education: 'UC Berkeley',
  photos: [PHOTO_SEEDS.men[5]],
  interests: ['Hiking', 'Cooking', 'Photography', 'Music', 'Travel'],
  values: ['Growth', 'Honesty', 'Humor', 'Adventure'],
  personalityTraits: ['Curious', 'Warm', 'Ambitious', 'Playful'],
  relationshipGoal: 'relationship',
  attachmentStyle: 'secure',
  loveLanguage: 'time',
  height: '6\'0"',
  drinking: 'Socially',
  smoking: 'Never',
  kids: 'Open to it',
  auraScore: 87,
  isVerified: true,
  lastActive: new Date().toISOString(),
};

export const PROFILES: UserProfile[] = [
  {
    id: 'p-1',
    name: 'Sophie',
    age: 26,
    gender: 'woman',
    location: 'San Francisco, CA',
    bio: 'Art director who finds beauty in unexpected places. I make sourdough on weekends and believe that every city has a best coffee shop waiting to be discovered. Let\'s find it together.',
    occupation: 'Art Director',
    education: 'RISD',
    photos: [PHOTO_SEEDS.women[0], PHOTO_SEEDS.women[4]],
    interests: ['Art', 'Coffee', 'Travel', 'Photography', 'Yoga'],
    values: ['Creativity', 'Freedom', 'Growth', 'Kindness'],
    personalityTraits: ['Creative', 'Thoughtful', 'Adventurous', 'Warm'],
    relationshipGoal: 'relationship',
    attachmentStyle: 'secure',
    loveLanguage: 'time',
    height: '5\'6"',
    drinking: 'Socially',
    smoking: 'Never',
    kids: 'Want someday',
    auraScore: 91,
    isVerified: true,
    lastActive: new Date(Date.now() - 3600000).toISOString(),
    distance: 2,
  },
  {
    id: 'p-2',
    name: 'Maya',
    age: 29,
    gender: 'woman',
    location: 'Oakland, CA',
    bio: 'Environmental scientist saving the planet by day, rock climber by weekend. I\'m looking for someone who appreciates both a good NPR podcast and dancing until 2am. Equal parts nerdy and adventurous.',
    occupation: 'Environmental Scientist',
    education: 'Stanford University',
    photos: [PHOTO_SEEDS.women[1], PHOTO_SEEDS.women[5]],
    interests: ['Rock Climbing', 'Hiking', 'Podcasts', 'Dancing', 'Cooking'],
    values: ['Sustainability', 'Adventure', 'Honesty', 'Health'],
    personalityTraits: ['Passionate', 'Analytical', 'Spontaneous', 'Grounded'],
    relationshipGoal: 'relationship',
    attachmentStyle: 'secure',
    loveLanguage: 'acts',
    height: '5\'7"',
    drinking: 'Rarely',
    smoking: 'Never',
    kids: 'Open to it',
    auraScore: 89,
    isVerified: true,
    lastActive: new Date(Date.now() - 7200000).toISOString(),
    distance: 8,
  },
  {
    id: 'p-3',
    name: 'Zara',
    age: 27,
    gender: 'woman',
    location: 'San Francisco, CA',
    bio: 'Startup founder building something I actually care about. I run half marathons, read 50 books a year, and have strong opinions about pizza. Looking for a partner, not a project.',
    occupation: 'Startup Founder',
    education: 'MIT',
    photos: [PHOTO_SEEDS.women[2], PHOTO_SEEDS.women[6]],
    interests: ['Running', 'Reading', 'Tech', 'Film', 'Wine'],
    values: ['Ambition', 'Growth', 'Independence', 'Humor'],
    personalityTraits: ['Ambitious', 'Intellectual', 'Passionate', 'Curious'],
    relationshipGoal: 'relationship',
    attachmentStyle: 'avoidant',
    loveLanguage: 'words',
    height: '5\'8"',
    drinking: 'Socially',
    smoking: 'Never',
    kids: 'Not sure yet',
    auraScore: 85,
    isVerified: true,
    lastActive: new Date(Date.now() - 1800000).toISOString(),
    distance: 4,
  },
  {
    id: 'p-4',
    name: 'Priya',
    age: 28,
    gender: 'woman',
    location: 'San Jose, CA',
    bio: 'UX designer who obsesses over tiny details. Board game nights, farmers markets, and cooking elaborate Sunday dinners are my love language. I want someone who notices the small things.',
    occupation: 'UX Designer',
    education: 'Carnegie Mellon',
    photos: [PHOTO_SEEDS.women[3], PHOTO_SEEDS.women[0]],
    interests: ['Board Games', 'Cooking', 'Art', 'Farmers Markets', 'Yoga'],
    values: ['Kindness', 'Community', 'Creativity', 'Family'],
    personalityTraits: ['Nurturing', 'Creative', 'Thoughtful', 'Empathetic'],
    relationshipGoal: 'relationship',
    attachmentStyle: 'secure',
    loveLanguage: 'acts',
    height: '5\'4"',
    drinking: 'Rarely',
    smoking: 'Never',
    kids: 'Want kids',
    auraScore: 93,
    isVerified: true,
    lastActive: new Date(Date.now() - 900000).toISOString(),
    distance: 18,
  },
  {
    id: 'p-5',
    name: 'Luna',
    age: 25,
    gender: 'woman',
    location: 'Berkeley, CA',
    bio: 'PhD student in cognitive neuroscience who still manages to have fun. Concerts, late-night diners, and heated debates about consciousness are my idea of a great time. Looking for intellectual spark + genuine warmth.',
    occupation: 'PhD Researcher',
    education: 'UC Berkeley',
    photos: [PHOTO_SEEDS.women[4], PHOTO_SEEDS.women[2]],
    interests: ['Concerts', 'Reading', 'Meditation', 'Cycling', 'Theater'],
    values: ['Education', 'Curiosity', 'Growth', 'Humor'],
    personalityTraits: ['Intellectual', 'Curious', 'Calm', 'Warm'],
    relationshipGoal: 'relationship',
    attachmentStyle: 'anxious',
    loveLanguage: 'words',
    height: '5\'5"',
    drinking: 'Socially',
    smoking: 'Never',
    kids: 'Open to it',
    auraScore: 88,
    isVerified: false,
    lastActive: new Date(Date.now() - 14400000).toISOString(),
    distance: 11,
  },
];

export const MATCHES: Match[] = [
  {
    id: 'm-1',
    profile: PROFILES[0],
    compatibilityScore: 94,
    compatibilityBreakdown: {
      values: 92,
      communication: 95,
      lifestyle: 91,
      interests: 88,
      goals: 97,
      emotional: 96,
    },
    matchedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    aiReason: 'You both want a long-term relationship and prefer consistent communication over mixed signals. Your values align around growth and creativity, and your routines support planning real time together. This match has strong fit on intent, communication style, and lifestyle pace.',
    isNew: false,
    conversation: [
      {
        id: 'msg-1',
        senderId: 'p-1',
        content: 'Your profile mentioned you make sourdough — I\'ve been failing at mine for 3 months 😅 Any tips?',
        timestamp: new Date(Date.now() - 86400000 * 2 + 3600000).toISOString(),
        type: 'text',
        read: true,
      },
      {
        id: 'msg-2',
        senderId: 'user-1',
        content: 'Ha! I\'ve been there. The secret is patience — and a good starter name. Mine is called Margaret.',
        timestamp: new Date(Date.now() - 86400000 * 2 + 7200000).toISOString(),
        type: 'text',
        read: true,
      },
      {
        id: 'msg-3',
        senderId: 'p-1',
        content: 'Margaret! I love that. Mine will be called Vincent. After Van Gogh obviously. I notice you also do photography — do you have a favorite subject?',
        timestamp: new Date(Date.now() - 86400000 + 3600000).toISOString(),
        type: 'text',
        read: true,
      },
      {
        id: 'msg-4',
        senderId: 'user-1',
        content: 'Architecture and street photography mostly. There\'s something about capturing a city at 6am before it wakes up.',
        timestamp: new Date(Date.now() - 86400000 + 5400000).toISOString(),
        type: 'text',
        read: true,
      },
      {
        id: 'msg-5',
        senderId: 'p-1',
        content: 'That\'s such a good answer. I\'d love to see your work sometime. Maybe over that coffee we keep almost mentioning? ☕',
        timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
        type: 'text',
        read: false,
      },
    ],
  },
  {
    id: 'm-2',
    profile: PROFILES[3],
    compatibilityScore: 91,
    compatibilityBreakdown: {
      values: 94,
      communication: 88,
      lifestyle: 90,
      interests: 85,
      goals: 95,
      emotional: 93,
    },
    matchedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    aiReason: 'You both are dating intentionally and care about building something stable. You each value thoughtful communication and shared experiences at home and with friends. This creates a practical fit for steady momentum, not just early chemistry.',
    isNew: true,
    conversation: [
      {
        id: 'msg-6',
        senderId: 'user-1',
        content: 'Hey! Your board game night mention immediately got me — what\'s your go-to game?',
        timestamp: new Date(Date.now() - 86400000 * 5 + 7200000).toISOString(),
        type: 'text',
        read: true,
      },
      {
        id: 'msg-7',
        senderId: 'p-4',
        content: 'Pandemic for strategy, Codenames for parties. You?',
        timestamp: new Date(Date.now() - 86400000 * 4).toISOString(),
        type: 'text',
        read: true,
      },
      {
        id: 'msg-8',
        senderId: 'user-1',
        content: 'Terraforming Mars person here — we might be compatible 😄',
        timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
        type: 'text',
        read: true,
      },
      {
        id: 'msg-9',
        senderId: 'p-4',
        content: 'Oh no, a fellow complexity-appreciator. We\'d never leave the table 😂 I also saw you cook — what\'s your signature dish?',
        timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
        type: 'text',
        read: false,
      },
    ],
  },
  {
    id: 'm-3',
    profile: PROFILES[1],
    compatibilityScore: 87,
    compatibilityBreakdown: {
      values: 88,
      communication: 82,
      lifestyle: 91,
      interests: 84,
      goals: 86,
      emotional: 89,
    },
    matchedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    aiReason: 'You both value honesty, active lifestyles, and relationships that grow through shared experiences. Your life rhythm and social energy look well matched, with similar balance between independence and connection. This match makes sense if you want clear communication and real follow-through.',
    isNew: false,
    conversation: [
      {
        id: 'msg-10',
        senderId: 'p-2',
        content: 'Rock climbing + software engineering — are you the person who also does bouldering problems at the gym while mentally debugging code?',
        timestamp: new Date(Date.now() - 86400000 * 7).toISOString(),
        type: 'text',
        read: true,
      },
      {
        id: 'msg-11',
        senderId: 'user-1',
        content: 'Guilty as charged 😅 How long have you been climbing?',
        timestamp: new Date(Date.now() - 86400000 * 6).toISOString(),
        type: 'text',
        read: true,
      },
    ],
  },
];

export const AI_CONVERSATION_TIPS = [
  'Ask about a specific detail from her photos — it shows genuine attention.',
  'Share something vulnerable — it creates real connection faster than small talk.',
  'Follow up on what she said about [her interest] — she seems passionate about it.',
  'This feels like a good moment to suggest coffee or a casual hangout.',
  'Use humor here — the conversation needs a lighter touch.',
];

export const DATE_IDEAS = [
  {
    title: 'Golden Hour Photo Walk',
    description: 'Explore the city together during the magic hour. You both love photography — make it a collaborative project.',
    category: 'outdoor' as const,
    estimatedTime: '2-3 hours',
    cost: 'free' as const,
  },
  {
    title: 'Farmers Market + Cook Together',
    description: 'Pick ingredients at the market, then cook a meal together. Perfect for your shared love of cooking.',
    category: 'food' as const,
    estimatedTime: '4-5 hours',
    cost: '$' as const,
  },
  {
    title: 'Hidden Coffee Shop Hunt',
    description: 'Map out 3 specialty coffee shops in the neighborhood and rate each one. A journey with a clear, fun goal.',
    category: 'food' as const,
    estimatedTime: '2-4 hours',
    cost: '$' as const,
  },
  {
    title: 'Museum After Dark',
    description: 'SFMOMA or de Young after-hours event. Art + evening atmosphere = memorable first impression.',
    category: 'culture' as const,
    estimatedTime: '3 hours',
    cost: '$$' as const,
  },
];
