// Daily Spark — AI-curated paired questions
// In production these would be generated by Claude based on each couple's compatibility profile

export interface SparkQuestion {
  id: string;
  question: string;
  category: 'values' | 'dreams' | 'memories' | 'fun' | 'deep' | 'hypothetical';
  followUp?: string; // shown after both answer
}

export interface SparkEntry {
  matchId: string;
  matchName: string;
  matchPhoto: string;
  compatScore: number;
  date: string; // ISO date string (day only)
  question: SparkQuestion;
  myAnswer: string | null;
  theirAnswer: string | null;
  bothAnswered: boolean;
  expiresAt: string; // ISO datetime
  streakDay: number;
}

export const QUESTION_BANK: SparkQuestion[] = [
  // Values
  { id: 'v1', question: "What's one thing you believe that most people around you don't?", category: 'values', followUp: "Values divergence is healthy — notice where your beliefs overlap and where they create interesting friction." },
  { id: 'v2', question: "What would you do with your life if money weren't a factor?", category: 'values', followUp: "This reveals what someone actually cares about when pressure is removed." },
  { id: 'v3', question: "Describe a moment when you changed your mind about something important.", category: 'values', followUp: "Intellectual flexibility is one of the strongest long-term compatibility signals." },

  // Dreams
  { id: 'd1', question: "Where do you picture yourself living in 10 years, and why there?", category: 'dreams', followUp: "Location compatibility matters more than people admit upfront." },
  { id: 'd2', question: "What's the version of yourself you're actively working toward right now?", category: 'dreams', followUp: "Growth direction is often more important than current status." },
  { id: 'd3', question: "What's one thing you want to experience before you're 40 that you haven't yet?", category: 'dreams', followUp: "Aspirations reveal what makes someone feel alive." },

  // Memories
  { id: 'm1', question: "What's a moment from your childhood that quietly shaped who you are?", category: 'memories', followUp: "Childhood moments are often the invisible architects of adult character." },
  { id: 'm2', question: "Who is the most interesting person you've ever met, and what made them that way?", category: 'memories', followUp: "Who you find interesting reveals what you value in people." },
  { id: 'm3', question: "What's a trip or experience you keep coming back to in your memory?", category: 'memories', followUp: "What we replay tells us what we're still processing or cherishing." },

  // Fun
  { id: 'f1', question: "What's your go-to order when you haven't decided yet — and does it ever change?", category: 'fun', followUp: "A small window into how someone makes decisions under low stakes." },
  { id: 'f2', question: "What skill do you wish you'd started learning at age 10?", category: 'fun', followUp: "A surprisingly revealing question about regret and curiosity." },
  { id: 'f3', question: "What's your most controversial food opinion?", category: 'fun', followUp: "Debate is healthy — and food opinions are a safe battlefield." },

  // Deep
  { id: 'dp1', question: "What do you think is the most underrated quality in a romantic partner?", category: 'deep', followUp: "This answer often reveals what someone has been missing in past relationships." },
  { id: 'dp2', question: "When do you feel most like yourself?", category: 'deep', followUp: "Context matters — 'at 6am running' and 'at 2am with friends' tell very different stories." },
  { id: 'dp3', question: "What's something you used to judge others for that you understand better now?", category: 'deep', followUp: "Empathy growth is one of the most attractive things a person can develop." },

  // Hypothetical
  { id: 'h1', question: "You can live anywhere in the world for one year, all expenses covered. Where, and what do you do there?", category: 'hypothetical', followUp: "Freedom of choice reveals a lot about someone's default self." },
  { id: 'h2', question: "You can have dinner with any person, living or dead. Who, and what's the first question you ask them?", category: 'hypothetical', followUp: "The question they'd ask reveals more than who they'd pick." },
  { id: 'h3', question: "Your future self sends you one piece of advice. What do you hope it says?", category: 'hypothetical', followUp: "We often already know the advice we need — this surfaces it." },
];

export const CATEGORY_COLORS: Record<SparkQuestion['category'], { bg: string; border: string; text: string; label: string }> = {
  values:       { bg: 'rgba(139,92,246,0.1)',  border: 'rgba(139,92,246,0.25)', text: '#c4b5fd', label: 'Values' },
  dreams:       { bg: 'rgba(251,191,36,0.1)',  border: 'rgba(251,191,36,0.25)', text: '#fde68a', label: 'Dreams' },
  memories:     { bg: 'rgba(244,63,94,0.1)',   border: 'rgba(244,63,94,0.25)',  text: '#fda4af', label: 'Memory' },
  fun:          { bg: 'rgba(52,211,153,0.1)',  border: 'rgba(52,211,153,0.25)', text: '#6ee7b7', label: 'Fun' },
  deep:         { bg: 'rgba(99,102,241,0.1)',  border: 'rgba(99,102,241,0.25)', text: '#a5b4fc', label: 'Deep' },
  hypothetical: { bg: 'rgba(236,72,153,0.1)',  border: 'rgba(236,72,153,0.25)', text: '#f9a8d4', label: 'Imagine' },
};

// Mock today's sparks for each match
const today = new Date().toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString();

export const TODAY_SPARKS: SparkEntry[] = [
  {
    matchId: 'm-1',
    matchName: 'Sophie',
    matchPhoto: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=200&q=80',
    compatScore: 94,
    date: today,
    question: QUESTION_BANK[13], // most underrated quality
    myAnswer: null,
    theirAnswer: null, // will be revealed when both answer
    bothAnswered: false,
    expiresAt: tomorrow,
    streakDay: 4,
  },
  {
    matchId: 'm-2',
    matchName: 'Priya',
    matchPhoto: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&q=80',
    compatScore: 91,
    date: today,
    question: QUESTION_BANK[3], // where in 10 years
    myAnswer: 'Honestly somewhere with real seasons — probably a city I can walk everywhere but escape to nature in 30 minutes. Portland, maybe. Or somewhere in Europe.',
    theirAnswer: 'I dream about a place where I can have a garden and still be close to a great food scene. Somewhere that feels like a community, not just a place.',
    bothAnswered: true,
    expiresAt: tomorrow,
    streakDay: 7,
  },
  {
    matchId: 'm-3',
    matchName: 'Maya',
    matchPhoto: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=200&q=80',
    compatScore: 87,
    date: today,
    question: QUESTION_BANK[6], // childhood moment
    myAnswer: null,
    theirAnswer: null,
    bothAnswered: false,
    expiresAt: tomorrow,
    streakDay: 2,
  },
];

// Past sparks (for archive view)
export const PAST_SPARKS: SparkEntry[] = [
  {
    matchId: 'm-1',
    matchName: 'Sophie',
    matchPhoto: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=200&q=80',
    compatScore: 94,
    date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    question: QUESTION_BANK[14], // judged others for
    myAnswer: 'I used to judge people who needed a lot of reassurance in relationships. Now I understand it usually comes from somewhere real, and most people are doing their best.',
    theirAnswer: 'Honestly? People who couldn\'t make decisions. Took me a long time to understand that sometimes indecision is just fear, not laziness. I\'m more patient with it now.',
    bothAnswered: true,
    expiresAt: new Date(Date.now() - 3600000).toISOString(),
    streakDay: 3,
  },
];

export const CONNECTION_STAGES = [
  { stage: 1, label: 'Matched',      desc: 'You both liked each other',                icon: '💫', unlocks: 'Messaging' },
  { stage: 2, label: 'Talking',      desc: '5+ messages exchanged',                    icon: '💬', unlocks: 'Daily Spark questions' },
  { stage: 3, label: 'Connected',    desc: '7 days of conversation',                   icon: '🌱', unlocks: 'Vinculo Moments (thinking of you)' },
  { stage: 4, label: 'Pre-Date',     desc: 'You\'ve agreed to meet',                   icon: '☕', unlocks: 'Pre-Date Question Card' },
  { stage: 5, label: 'Met',          desc: 'First date happened',                      icon: '✨', unlocks: 'Chemistry Check-in + Date Vault' },
  { stage: 6, label: 'Growing',      desc: 'Multiple dates, strong chemistry',         icon: '🔥', unlocks: 'AI Relationship Insights' },
  { stage: 7, label: 'Exclusive',    desc: 'Both chose each other',                    icon: '💍', unlocks: 'Couples Mode — full Candle-style features' },
];
